name: Merge ICS Calendars

on:
  schedule:
    - cron: '0 23 * * *'     # 23:00 UTC nightly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests icalendar pytz

      - name: Fetch now-streaming movies
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: python fetch_movies.py

      - name: Merge calendars
        run: python merge.py

      - name: Commit merged calendar
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/merged.ics
          git commit -m "Update merged calendar" || echo "No changes to commit"
          git push
