name: Merge ICS Calendars

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2:00 AM UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install icalendar requests

      - name: Merge calendars
        run: python merge.py

      - name: Commit merged calendar
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add merged.ics
          git commit -m "Update merged calendar" || echo "No changes to commit"
          git push
          
