permissions:
  contents: write

name: Merge ICS Calendars

on:
  schedule:
    - cron: '0 23 * * *'  # 23:00 UTC → 05:00 BDT next day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        # By default, actions/checkout@v3 will pick up the GITHUB_TOKEN that has
        # the “contents: write” permission we just declared.

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests icalendar pytz


      - name: Merge calendars
        run: python merge.py

      - name: Commit merged calendar
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docs/merged.ics
          git commit -m "Update merged calendar" || echo "No changes to commit"
          git push
